### PR TITLE
Placed metrics/README.md file in a more appropriate place

### PR DESCRIPTION
**Pull request by Ankit152**
Signed-off-by: Ankit Kurmi <ankitkurmi152@gmail.com>

## Description

Placed `metrics/README.md` into a more appropriate place.

### CODE REVIEW

**Review by chaodaiG — APPROVED** [review]

**Comment by listx** [comment]
@Ankit152 looks like this PR was a NOP (I can't see a Metrics heading in the docs site). Can you do a fixup to this to follow the pattern established in #13 ?

**Comment by Ankit152** [comment]
@listx seems like the readme is missing some lines similar to these:
```
---
title: "Deck"
weight: 10
description: >
  Shows what jobs are running or have recently run in prow
---
```
Just confirming before making any changes.

**Comment by listx** [comment]
> @listx seems like the readme is missing some lines similar to these:
> 
> ```
> ---
> title: "Deck"
> weight: 10
> description: >
>   Shows what jobs are running or have recently run in prow
> ---
> ```
> 
> Just confirming before making any changes.

Yes. But also, when you push up a new change you should be able to double-check against the preview of the generated website, courtesy of the "netlify" bot, as in [the comment above](https://github.com/kubernetes-sigs/prow/pull/12#issuecomment-1181461752).

**Pull request merged**
