### PR TITLE
chore: update deps for sigs.k8s.io/controller-runtime@v0.16.3 - step 1

### PR DESCRIPTION
**Pull request by psalajova**
After prow has moved from kubernetes/test-infra, this PR recreates @danilo-gemoli 's PR (https://github.com/kubernetes/test-infra/pull/32330) which is a part of the `sigs.k8s.io/controller-runtime@v0.16.3` upgrade effort. 

Check the issue at https://github.com/kubernetes/test-infra/issues/32328

The following modules have been updated:
```
- github.com/emicklei/go-restful/v3@v3.11.0
- github.com/evanphx/json-patch@v5.6.0+incompatible
- github.com/fsnotify/fsnotify@v1.6.0
- github.com/go-kit/log@v0.2.1
- github.com/go-logr/zapr@v1.2.4
- github.com/go-openapi/jsonreference@v0.20.2
- github.com/google/gnostic-models@v0.6.8
```

`github.com/google/gnostic-models@v0.6.8` is being removed as soon as go mod tidy is issued. I guess that's why at this point it is just an indirect dependency not being used by anyone/anything.

/label tide/merge-method-squash

### CODE REVIEW

**Comment by jihoon-seo** [comment]
The [test log](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_prow/106/pull-prow-verify-lint/1779886925075714048) says that:

> ERROR: the following file(s) cannot be executed:
./vendor/cloud.google.com/go/internal/version/update_version.sh
./vendor/cloud.google.com/go/storage/emulator_test.sh
./vendor/github.com/cespare/xxhash/v2/testall.sh
./vendor/github.com/emicklei/go-restful/v3/bench_test.sh
./vendor/github.com/emicklei/go-restful/v3/coverage.sh
./vendor/github.com/json-iterator/go/build.sh
./vendor/github.com/json-iterator/go/test.sh
./vendor/github.com/modern-go/concurrent/test.sh
./vendor/go.uber.org/zap/checklicense.sh
./vendor/golang.org/x/crypto/curve25519/internal/field/sync.sh
./vendor/golang.org/x/sys/plan9/mkall.sh
./vendor/golang.org/x/sys/plan9/mkerrors.sh
./vendor/golang.org/x/sys/plan9/mksysnum_plan9.sh
./vendor/golang.org/x/sys/unix/mkall.sh
./vendor/golang.org/x/sys/unix/mkerrors.sh
./vendor/google.golang.org/appengine/internal/regen.sh
./vendor/google.golang.org/appengine/travis_install.sh
./vendor/google.golang.org/appengine/travis_test.sh
./vendor/google.golang.org/grpc/codegen.sh
./vendor/google.golang.org/grpc/regenerate.sh
./vendor/google.golang.org/grpc/vet.sh
Please run 'make update-file-perms'
ERROR: .sh files permissions failed

So to resolve build error, it seems that we need to update the permission of those files by running `make update-file-perms`..

**Comment by petr-muller** [comment]
/hold

@psalajova we don't vendor deps in Prow, please drop the `go mod vendor` commits

**Comment by danilo-gemoli** [comment]
Ah, [missing rule](https://github.com/kubernetes/test-infra/blob/dcdd96dcd594aba93a3934225f356c699cda88e9/.gitignore#L19) in `.gitignore`. Maybe we can add it even if it's not really in the scope of this PR...

**Comment by petr-muller** [comment]
> Maybe we can add it even if it's not really in the scope of this PR...
SGTM

**Comment by psalajova** [comment]
https://github.com/kubernetes-sigs/prow/pull/101 should fix the failing tests

**Comment by petr-muller** [comment]
I have resolved the `.gitignore` config; merge commit will be squashed so :shrug: 

Let's wait a day or two though, for the case https://github.com/kubernetes-sigs/prow/pull/101 needs to be reverted, so that we don't make it harder if needed.

**Comment by upodroid** [comment]
Hey, #101 has been successfully deployed and has been running in prod for a few days.

**Review by petr-muller — APPROVED** [review]
:shipit:

**Pull request merged**
