### PR TITLE
docs: Migrate ghProxy docs to Prow website

### PR DESCRIPTION
**Pull request by jihoon-seo**
This PR adds ghProxy (and its related) pages to Prow website.
- This PR does not add ghProxy in Prow website's 'Components' directory, because ghProxy seems to be not an component of Prow.
  (Change may apply.)

[Preview]
- [ghProxy](https://deploy-preview-107--k8s-prow.netlify.app/docs/ghproxy/)
  - [ghCache](https://deploy-preview-107--k8s-prow.netlify.app/docs/ghproxy/ghcache/)
  - [Additional throttling algorithm](https://deploy-preview-107--k8s-prow.netlify.app/docs/ghproxy/throttling-algorithm/)

[Screenshot of left navbar]
image

### CODE REVIEW

**Comment by listx** [comment]
Hi @jihoon-seo, thanks for this PR. I notice that these documents are based on https://github.com/kubernetes-sigs/prow/tree/main/ghproxy. We should probably also deprecate the original ones and treat the ones you added as the new source of truth.

**Comment by jihoon-seo** [comment]
Hello @listx, thank you for your comment!
I reflected your comment by replacing the original ones with deprecation notices; 
please see the 2nd commit fd53abf.

We might
- add file deletion notice to deprecation notice, like: `This file will be deleted on 2024-05-31.` (Date may change)
- or alternatively, just delete the original files (without leaving deprecation notice)

PTAL!

**Comment by listx** [comment]
Thanks!

/lgtm
/approve

/hold ? (maybe you want more reviews?)

**Comment by jihoon-seo** [comment]
@listx Thank you!
Let me unhold this. 😊
/unhold

**Pull request merged**
