### PR TITLE
Sync Prow commits from the test-infra repo

### PR DESCRIPTION
**Pull request by timwangmusic**
Extract Prow commit history from test-infra up to 1/14/2024 and merge them to the Prow repo.

Script to reproduce this PR:
```
git clone https://github.com/kubernetes/test-infra.git
cd test-infra
git-filter-repo --path prow/
# $YOUR_PROW_FORK is your forked repo for https://github.com/kubernetes-sigs/prow
git remote add target $YOUR_PROW_FORK
git fetch target
# move to the target/main branch
git checkout target/main
git switch -c tmp
# merge the local master branch
git merge master --allow-unrelated-histories
git push --set-upstream target tmp
```

/assign: @listx @cjwagner @airbornepony

### CODE REVIEW

**Comment by listx** [comment]
/lgtm
/hold

Below are some comments for improvement for the next time we need to do this again.

I think your script can be improved like this:

```
# Clone old repo. Let's call it $old_prow.
git clone https://github.com/kubernetes/test-infra.git
# Strip down master branch of $old_prow to only have commits that touch the the /prow directory.
cd test-infra
git-filter-repo --path prow

# Navigate to your local clone of https://github.com/kubernetes-sigs/prow.
# Let's call this $new_prow.
cd $new_prow
# Check out a new "sync" branch that we want to create a PR from.
git branch sync origin/main
git checkout sync

# Import commits from old_prow/master into "sync" inside $new_prow.
git remote add old_prow $old_prow
git fetch old_prow
git merge old_prow/master
```

This way, the merge commit will have the self-descriptive text `Merge remote-tracking branch 'old_prow/master' into sync` instead of the PR here which has just `Merge branch 'master' into HEAD` which is a bit confusing because it's not clear which `master` branch we are talking about.

It would be even better if you could convert the above into a real bash script and check it into this repo for record-keeping. Then you could just run the script instead of doing things manually.

Aside: it looks like the `--allow-unrelated-histories` flag is not required, at least on the Git version I am using `2.43.0.381.gb435a96ce8-goog`.

**Comment by timwangmusic** [comment]
> /lgtm /hold
> 
> Below are some comments for improvement for the next time we need to do this again.
> 
> I think your script can be improved like this:
> 
> ```
> # Clone old repo. Let's call it $old_prow.
> git clone https://github.com/kubernetes/test-infra.git
> # Strip down master branch of $old_prow to only have commits that touch the the /prow directory.
> cd test-infra
> git-filter-repo --path prow
> 
> # Navigate to your local clone of https://github.com/kubernetes-sigs/prow.
> # Let's call this $new_prow.
> cd $new_prow
> # Check out a new "sync" branch that we want to create a PR from.
> git branch sync origin/main
> git checkout sync
> 
> # Import commits from old_prow/master into "sync" inside $new_prow.
> git remote add old_prow $old_prow
> git fetch old_prow
> git merge old_prow/master
> ```
> 
> This way, the merge commit will have the self-descriptive text `Merge remote-tracking branch 'old_prow/master' into sync` instead of the PR here which has just `Merge branch 'master' into HEAD` which is a bit confusing because it's not clear which `master` branch we are talking about.
> 
> It would be even better if you could convert the above into a real bash script and check it into this repo for record-keeping. Then you could just run the script instead of doing things manually.
> 
> Aside: it looks like the `--allow-unrelated-histories` flag is not required, at least on the Git version I am using `2.43.0.381.gb435a96ce8-goog`.

But in this script, we are not actually using the local copy of the `$old_prow`.

**Comment by listx** [comment]
> But in this script, we are not actually using the local copy of the `$old_prow`.

We are using it, right? See last 3 lines of the script.

**Comment by timwangmusic** [comment]
> > But in this script, we are not actually using the local copy of the `$old_prow`.
> 
> We are using it, right? See last 3 lines of the script.

When I tried to run the last command of your version, I got this `merge: old_prow/master - not something we can merge`.

**Comment by listx** [comment]
@timwangmusic Here's a new script called `sync-prow.sh` I wrote which is the same as the old one. It could be that your version of Git is too old, or perhaps you were using a dirty repo. I ran the script and it works without problems.

```
#!/usr/bin/env bash

set -euo pipefail

old_prow="$PWD/test-infra"
new_prow="$PWD/prow"

# Clone old prow.
if [[ ! -d "$old_prow" ]]; then
    git clone https://github.com/kubernetes/test-infra.git
fi
# Strip down master branch of $old_prow to only have commits that touch the the /prow directory.
pushd $old_prow
git-filter-repo --path prow
popd

# Clone new prow.
if [[ ! -d "$new_prow" ]]; then
    git clone https://github.com/kubernetes-sigs/prow
fi
cd $new_prow
# Check out a new "sync" branch that we want to create a PR from.
git branch sync origin/main
git checkout sync

# Import commits from old_prow/master into "sync" inside $new_prow.
git remote add old_prow $old_prow
git fetch old_prow
git merge old_prow/master
```

and running it gives me:

```
 $ ./sync-prow.sh
~/ztmp/test-infra ~/ztmp
Parsed 15720 commits
New history written in 3.30 seconds; now repacking/cleaning...
Repacking your repo and cleaning out old unneeded objects
HEAD is now at ba098cda6 Merge pull request #31671 from airbornepony/resultstore-config-cleanup
Enumerating objects: 102266, done.
Counting objects: 100% (102266/102266), done.
Delta compression using up to 48 threads
Compressing objects: 100% (25132/25132), done.
Writing objects: 100% (102266/102266), done.
Total 102266 (delta 62738), reused 102266 (delta 62738), pack-reused 0 (from 0)
Completely finished after 4.48 seconds.
~/ztmp
Cloning into 'prow'...
remote: Enumerating objects: 103201, done.
remote: Counting objects: 100% (3132/3132), done.
remote: Compressing objects: 100% (583/583), done.
remote: Total 103201 (delta 2451), reused 2873 (delta 2404), pack-reused 100069
Receiving objects: 100% (103201/103201), 35.15 MiB | 20.92 MiB/s, done.
Resolving deltas: 100% (62990/62990), done.
branch 'sync' set up to track 'origin/main'.
Switched to branch 'sync'
Your branch is up to date with 'origin/main'.
remote: Enumerating objects: 168, done.
remote: Counting objects: 100% (146/146), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 81 (delta 48), reused 58 (delta 25), pack-reused 0 (from 0)
Unpacking objects: 100% (81/81), 13.28 KiB | 424.00 KiB/s, done.
From /usr/local/google/home/linusa/ztmp/test-infra
 * [new branch]          master     -> old_prow/master
hint: Waiting for your editor to close the file... t
nil
Merge made by the 'ort' strategy.
 prow/apis/prowjobs/v1/types.go                    |  23 ++++++++-----------
 prow/apis/prowjobs/v1/zz_generated.deepcopy.go    |  26 ++++-----------------
 prow/cmd/sinker/main.go                           | 149 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 prow/cmd/sinker/main_test.go                      | 113 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 prow/config/config.go                             |  14 ++++++++---
 prow/config/config_test.go                        | 123 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 prow/config/prow-config-documented.yaml           |   6 +++++
 prow/crier/controller.go                          |   4 +++-
 prow/crier/reporters/resultstore/reporter.go      |   4 ----
 prow/crier/reporters/resultstore/reporter_test.go |  32 --------------------------
 prow/pjutil/pjutil.go                             |   3 +++
 prow/pjutil/pjutil_test.go                        |   6 +++++
 prow/pod-utils/clone/clone.go                     |  19 ++++++++++++---
 prow/pod-utils/clone/clone_test.go                |  36 +++++++++++++++++++++++++++++
 prow/tide/github.go                               |   9 ++++----
 15 files changed, 486 insertions(+), 81 deletions(-)
```

When it executed the last command, I was dropped into my editor to compose the commit message for the merge commit, so the script requires human interaction. You could improve it to give a commit message on the command line so that you can run this script without requiring human input for the last command.

**Pull request merged**
