### PR TITLE
Add Prow as a subdirectory

### PR DESCRIPTION
**Pull request by timwangmusic**
The Prow directory contains all the current source code from k8s/test-infra with commit history.

Steps to recreate the change:
* Install the [git-filter-repo](https://github.com/newren/git-filter-repo) tool to your machine
* Execute the following shell script
```  
git clone https://github.com/kubernetes/test-infra.git
cd test-infra
git-filter-repo --path prow/
# $YOUR_PROW_FORK is your forked repo for https://github.com/kubernetes-sigs/prow
git remote add target $YOUR_PROW_FORK
git checkout main
# You are now on the target/main branch and then merge the local master branch
git merge master --allow-unrelated-histories
git push target main
```

/assign @cjwagner @listx @airbornepony

### CODE REVIEW

**Comment by cjwagner** [comment]
> * In the test-infra folder, execute command: `git checkout main`
> * Execute command: `git merge main`

This doesn't sound right. This would merge main into main, doing nothing. Can you clarify the steps you took if I'm misunderstanding or fix this if I'm not?

**Comment by timwangmusic** [comment]
> > * In the test-infra folder, execute command: `git checkout main`
> > * Execute command: `git merge main`
> 
> This doesn't sound right. This would merge main into main, doing nothing. Can you clarify the steps you took if I'm misunderstanding or fix this if I'm not?
> 
> It is important for this to be well documented and reproducible since we'll need to redo this to sync the latest changes right before we make this repo the source of truth.
> 
> FWIW the diff looks correct, at least as far as I can tell with a 281,449 line diff 😄

Yeah so we are on the `master` branch of the processed test-infra repo, and we merge the `main` branch from the last `checkout` command. This procedure is highly reproducible 😄.

**Comment by cjwagner** [comment]
> Yeah so we are on the `master` branch of the processed test-infra repo, and we merge the `main` branch from the last `checkout` command.

There is no mention of `master` in the PR body text. I'm saying that if you check out a branch and then try to merge that same branch it will do nothing or error since you aren't merging any new commits so those instructions must be wrong.

The test-infra repo doesn't even have a `main` branch so the `git checkout main` command would fail, right?

It would also help if you could clarify what we should expect the `git-filter-repo` command to do. Does that create the `main` branch that you are checking out? (The docs for it don't appear to suggest that.) Does it filter the commit history in place, and if so, why is a merge needed?

> This procedure is highly reproducible 😄.

That's great to hear. I would like it to be documented accurately here though. I don't think these instructions would reproduce this PR in their current state.

**Comment by listx** [comment]
> > > * In the test-infra folder, execute command: `git checkout main`
> > > * Execute command: `git merge main`
> > 
> > 
> > This doesn't sound right. This would merge main into main, doing nothing. Can you clarify the steps you took if I'm misunderstanding or fix this if I'm not?
> > It is important for this to be well documented and reproducible since we'll need to redo this to sync the latest changes right before we make this repo the source of truth.
> > FWIW the diff looks correct, at least as far as I can tell with a 281,449 line diff 😄
> 
> Yeah so we are on the `master` branch of the processed test-infra repo, and we merge the `main` branch from the last `checkout` command. This procedure is highly reproducible 😄.

The easiest thing to do is just write a short Bash script and then say "here, run this on your machine to get exactly what I got, modulo some more new commits (if any)". You've already given mostly precise manual instructions so the conversion should be easy. You can assume that `git` and `git-filter-repo` tools are already installed in your script. The `YOUR_FORK` you mention could be an environment variable or argument.

**Comment by timwangmusic** [comment]
> > > > * In the test-infra folder, execute command: `git checkout main`
> > > > * Execute command: `git merge main`
> > > 
> > > 
> > > This doesn't sound right. This would merge main into main, doing nothing. Can you clarify the steps you took if I'm misunderstanding or fix this if I'm not?
> > > It is important for this to be well documented and reproducible since we'll need to redo this to sync the latest changes right before we make this repo the source of truth.
> > > FWIW the diff looks correct, at least as far as I can tell with a 281,449 line diff 😄
> > 
> > 
> > Yeah so we are on the `master` branch of the processed test-infra repo, and we merge the `main` branch from the last `checkout` command. This procedure is highly reproducible 😄.
> 
> The easiest thing to do is just write a short Bash script and then say "here, run this on your machine to get exactly what I got, modulo some more new commits (if any)". You've already given mostly precise manual instructions so the conversion should be easy. You can assume that `git` and `git-filter-repo` tools are already installed in your script. The `YOUR_FORK` you mention could be an environment variable or argument.

@cjwagner @listx I took Linus suggestion and move the commands in a shell script and put it in the PR description. There were some error in the previous version. And the current script is the correct one.

**Review by cjwagner — APPROVED** [review]

**Comment by cjwagner** [comment]
Merge is blocked by https://github.com/kubernetes-sigs/prow/issues/68

**Comment by cjwagner** [comment]
> /verify-owners

The postsubmit job to add the new members had just started when that was run. Should work now.
/verify-owners

**Pull request merged**
