### PR TITLE
trigger: improve experience of guided comment

### LINKED ISSUE #321: trigger: Improve experience of guided comment
https://github.com/kubernetes-sigs/prow/blob/b21d1cf485474d6da2623ccc40849e2c8b24b2e5/pkg/pjutil/help.go#L75

Maybe we can make the line copied able in GitHub PR comment.

Many people are used to copying the instructions given in the comments and then creating new trigger comments, but it is easy to copy the leading blank characters, which will cause the `trigger` plugin to reject such instructions. By introducing the click-copy feature, this situation will be effectively avoided, and it will be more convenient to use.

In terms of the solution, this does not need to rely on any other third-party functions. GitHub markdown itself supports this capability. We only need to fine-tune the markdown format to do it.

The following is a comparison of the effects.

Before:
```md
@wuhuizuo: The specified target(s) for `/test` were not found. The following commands are available to trigger required jobs:

* `/test pull-unit-test`
```
image

After:
```md
@wuhuizuo: The specified target(s) for `/test` were not found. The following commands are available to trigger required jobs:

*     /test pull-unit-test
```
image

The different between the two markdown contents:
```diff
3c3
< * `/test pull-unit-test`
---
> *     /test pull-unit-test
```

### PR DESCRIPTION
**Pull request by wuhuizuo**
Fixes #321

Signed-off-by: wuhuizuo <wuhuizuo@126.com>

### CODE REVIEW

**Review by petr-muller — APPROVED** [review]

**Comment by petr-muller** [comment]
/lgtm cancel

Needs unit tests fixed

**Comment by wuhuizuo** [comment]
I fixed the unit test, and run them passed in local except the `pkg/kube` package.

> /lgtm cancel
> 
> Needs unit tests fixed

**Comment by wuhuizuo** [comment]
My development env is on a kubernetes pod, the `pkg/kube` test can not pass on my env.

**Pull request merged**
