### PR TITLE
Use new Go module name in Prow source files

### PR DESCRIPTION
**Pull request by timwangmusic**
The new Go module name is sigs.k8s.io/prow. In this change:
- Replace module names from k8s.io/test-infra to sigs.k8s.io/prow for Prow source files
- Added the tools package (copied from the k8s.io/test-infra repo)

/assign: @cjwagner @listx @airbornepony

### CODE REVIEW

**Comment by cjwagner** [comment]
Just as in https://github.com/kubernetes-sigs/prow/pull/67 we'll need to be able to redo this to sync the latest Prow changes before we make this repo the source of truth. So the same feedback of making this repeatable via a shell script applies here. Ideally when we're ready to sync the latest Prow changes and make the switch, we can run one script to redo all the setup.

**Comment by listx** [comment]
Taking a step back from this PR, I'm interested in how to do the actual switch over to this repo as the source of truth. What are the exact steps we need to do in order to make the switch happen? Could you explain in the PR description what will need to happen next, etc?

**Comment by timwangmusic** [comment]
closing due to out of date.

**Pull request closed without merging**
