### PR TITLE
Remove redundant go.mod file in /prow directory

### PR DESCRIPTION
**Pull request by timwangmusic**
The `prow/go.mod` file is identical to the one at the top level folder.

### CODE REVIEW

**Review by airbornepony — COMMENTED** [review]
Can you explain why the files are present in test-infra, and why it is okay to remove them in this repo? Thanks.

**Comment by timwangmusic** [comment]
> Can you explain why the files are present in test-infra, and why it is okay to remove them in this repo? Thanks.

You mean the go.mod is the same as those in test-infra?

**Comment by airbornepony** [comment]
> > Can you explain why the files are present in test-infra, and why it is okay to remove them in this repo? Thanks.
> 
> You mean the go.mod is the same as those in test-infra?

There are files with the same name and location (beside the "prow" direcotory) in test-infra. I don't know if they have the same content. In any case, I want to know why the files are there--how they came to be.

Were they created by running certain tools? Will they come back when they are run again?

**Comment by listx** [comment]
> The `prow/go.mod` file is identical to the one at the top level folder.

Looks like you added these redundant files in https://github.com/kubernetes-sigs/prow/pull/70. Instead of creating a new commit like this, I suggest you close this PR and revert #70. That way the context is preserved and it will be simpler to review (reviewers need context to review PRs effectively --- please keep this in mind).

**Comment by timwangmusic** [comment]
> > The `prow/go.mod` file is identical to the one at the top level folder.
> 
> Looks like you added these redundant files in #70. Instead of creating a new commit like this, I suggest you close this PR and revert #70. That way the context is preserved and it will be simpler to review (reviewers need context to review PRs effectively --- please keep this in mind).

Created a revert: [#81](https://github.com/kubernetes-sigs/prow/pull/81)

**Pull request closed without merging**
