### PR TITLE
Don't embed tekton schema in ProwJob CRD

### PR DESCRIPTION
**Pull request by maboehm**
The CRD has become too large for standard kubernetes / etcd installations. With this change, the CRD generation is instructed to treat all `tektoncd` types as schema-less (while instructing the apiserver to keep unknown fields). This reduces the size down to around 500KB

Seems like upstream, tekton is doing something similar, their CRD does not have a schema: https://github.com/tektoncd/pipeline/blob/main/config/300-crds/300-pipelinerun.yaml#L62-L72

I also updated the `admission` component to use strict validation and to be able to handle CREATE requests as well. With this component deployed, you would get at least some level of safety back, even if the response is a bit lacking right now:

```
# non-existing field
Error from server: error when creating "test/integration/test/testdata/valid_bare_prowjob.yaml": admission webhook "prowjob-validator.prow.k8s.io" denied the request: decode new: strict decoding error: unknown field "spec.pipeline_run_spec.foo"

# wrong type on field
Error from server: error when creating "test/integration/test/testdata/valid_bare_prowjob.yaml": admission webhook "prowjob-validator.prow.k8s.io" denied the request: decode new: json: cannot unmarshal string into Go struct field PipelineRunSpec.spec.pipeline_run_spec.pipelineRef of type v1beta1.PipelineRef
```

(I also did not see the admission component installed in https://github.com/kubernetes/test-infra/tree/master/config/prow so not sure who uses it. We dont have it in our env.)

Fixes https://github.com/kubernetes-sigs/prow/issues/181

### CODE REVIEW

**Comment by matthyx** [comment]
awesome @maboehm can you check the CLA?

**Comment by maboehm** [comment]
Just an additional comment: we dont use the tekton stuff in our setup, so might be worth double checking (but I did check that the fields are in fact preserved, so confidence is high)

**Comment by maboehm** [comment]
It's been two weeks, should we just move forward?

**Comment by matthyx** [comment]
> It's been two weeks, should we just move forward?

I'd say yes.
/approve
/hold

**Pull request merged**
