### PR TITLE
Revert "Revert "`gangway`: add status change endpoint""

### PR DESCRIPTION
**Pull request by Prucek**
Reverts kubernetes-sigs/prow#156

### CODE REVIEW

**Comment by petr-muller** [comment]
FYI these are the failures we saw (and why I reverted the PR):

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_prow/155/pull-prow-integration/1791473589053034496
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_prow/155/pull-prow-integration/1791466104812474368

**Comment by Prucek** [comment]
I didn't close it, it closed on its own

**Comment by petr-muller** [comment]
@Prucek That's a fun little GitHub quirk. You have [force pushed](https://github.com/kubernetes-sigs/prow/pull/158#event-12879434308) the bca239a commit to be the tip of this PR:

> [Prucek](https://github.com/Prucek) [force-pushed](https://github.com/kubernetes-sigs/prow/compare/d07157db1b12ef19c40e0856caacae8bef922644..bca239a039f04dc0fe2003673633238bad70835b) the revert-156-revert-116-mass-job-status-change-api branch from[ d07157d ](https://github.com/kubernetes-sigs/prow/commit/d07157db1b12ef19c40e0856caacae8bef922644)to bca239a

Now, bca239a is the commit that was merged as a tip of the original (reverted) PR #116: https://github.com/kubernetes-sigs/prow/pull/116/commits

Which means this PR #158 would be a duplicate of an already closed PR #116 and therefore GitHub closes it too (normally this can happen when you have two open PRs trying to merge identical set of commits - once one of them merges, GitHub closes the other as well).

**Pull request closed without merging**
